// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiTnmXain_Y9xBxNKV8G1IOvZCjzCwgJo',
    appId: '1:815658870442:android:1a3aac74a12f19f3ffd2d3',
    messagingSenderId: '815658870442',
    projectId: 'unswipe-5a567',
    databaseURL: 'https://unswipe-5a567-default-rtdb.firebaseio.com',
    storageBucket: 'unswipe-5a567.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMfXDvROHSNn-EqTm3JxgV5Wd85-bUUw8',
    appId: '1:815658870442:ios:e3d51b56df1a4186ffd2d3',
    messagingSenderId: '815658870442',
    projectId: 'unswipe-5a567',
    databaseURL: 'https://unswipe-5a567-default-rtdb.firebaseio.com',
    storageBucket: 'unswipe-5a567.appspot.com',
    iosBundleId: 'com.abhilashi.unswipe',
  );

}